name: Build and Deploy to SSH Server

on:
  push:
    branches:
      - main # or the branch you want to trigger on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # or your desired version

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: Build the code
      run: yarn build

    # - name: Deploy to SSH Server
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     key: ${{ secrets.SSH_KEY }}
    #     source: "path/to/your/build/directory/*" # replace with your build directory path
    #     target: "/path/on/ssh/server" # replace with your desired path on the SSH server
